name: 'Check Branch Name'
description: 'check the pull request branch name follows the gitflow naming convention'
author: 'Mahmoud Almasri'
runs:
  using: "composite"
  steps:
    - run: |
        if ! [[ "$(echo ${GITHUB_HEAD_REF} | cut -d "/" -f1)" =~ (feature|hotfix|bugfix|release) ]]; then
          echo "Your branch name does not start with one of the following: feature/, hotfix/, bugfix, or release/."
          exit 1
        elif [[ "$(echo ${GITHUB_HEAD_REF} | cut -d "/" -f1)" == "hotfix" && ! "$(echo ${GITHUB_BASE_REF})" =~ (master|main) ]]; then
          echo "Your branch is a hotfix, but your base branch is not master or main; you can't hotfix any other branch."
          exit 1
        else
          echo "Your branch name follows the gitflow naming convention."
        fi 
      shell: bash
branding:
  icon: 'git-branch'  
  color: 'orange'
